.github/workflows/publish-preview.yml
docs/contributing.md

This PR adds a `TODO` note to the publish preview builds script to inform contributors that the script is currently broken and needs to be fixed. Additionally, the relevant documentation is updated to notify contributors about the issue and links to the related GitHub issue for tracking.
Fixes: https://github.com/MetaMask/metamask-design-system/issues/37
1. Read the updated documentation and check the link to the related issue.
2. Search the codebase for other instances where similar `TODO` notes might be necessary.
3. Confirm that the `TODO` note is visible in the relevant script file.

chore: adding to do note to preview builds script and docs

---

package.json
yarn.config.cjs

This pull request modifies the monorepo configuration to add and exclude the `docs/` workspace from monorepo-wide constraints and linting checks, such as those applied to package names. The `docs` workspace, which will contain our Storybook for React and React Native components, does not require these checks. The goal is to streamline the configuration and avoid applying unnecessary constraints to this workspace.
This PR updates the workspaces in `package.json` and relevant configuration in `yarn.config.cjs` to ensure that the `docs` workspace is ignored, while other workspaces remain unaffected by this change.
Fixes: https://github.com/MetaMask/metamask-design-system/issues/28
1. Run the linting process across the monorepo.
2. Verify that the `docs` workspace is excluded from linting …

chore: updating yarn config to ignore docs workspace for package.json checks

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/general_issue.md

This pull request adds a new issue templates for the `metamask-design-system` repository for general and bug. This template will simplify the process of creating issues related to design system tasks and ensure the `team-design-system` label is applied automatically.
- Created a new `ISSUE_TEMPLATE` in the `.github` directory.
- Used the general issue template from the design tokens repository as a base.
- Configured the template to apply the `team-design-system` label by default.
- Structured the template with sections for:
- Description
- Technical details
- Acceptance criteria
- References
Fixes: https://github.com/MetaMask/metamask-design-system/issues/2
1. Navigate to the `metamask-design-system` repository.
2. Create a new issue using the template.
3. Confirm that the …

chore: adding issue templates for general and bug issues

---

apps/storybook-react/stories/Shadows.stories.tsx
packages/design-system-tailwind-preset/src/index.test.ts
packages/design-system-tailwind-preset/src/index.ts
packages/design-system-tailwind-preset/src/shadows.test.ts
packages/design-system-tailwind-preset/src/shadows.ts

This pull request adds new shadow tokens to the `design-system-tailwind-preset` package. The shadow tokens are derived from the design token CSS variables, and include both color and size definitions. These tokens will generate Tailwind utility classes that ensure consistent shadow styles across components. The shadow configuration has been imported into the index preset for global use.
Fixes: https://github.com/MetaMask/metamask-design-system/issues/57
1. Run `yarn build && yarn` to build and install the local version of the tailwind preset in `storybook-react`
2. Run storybook using `yarn storybook`
3. See the shadows stories
4. Apply shadow utility classes (`shadow-default`, `shadow-primary`, `shadow-error`, etc.) to verify color.
5. Apply shadow size classes (`shadow-xs`, `shadow-sm`, …

feat: adding shadow to tailwind preset

---

docs/package-migration-process-guide.md

This PR removes the section regarding disabling `dependabot` alerts and updates from the migration guide documentation, based on organizational requirements discussed in this [Slack thread](https://consensys.slack.com/archives/C01V1L10W2E/p1731097509734129). It was determined that this step is no longer necessary because:
- Dependabot alerts cannot be disabled at the repository level due to new organizational rules.
- Disabling Dependabot alerts would ultimately be redundant, as the repository will be archived after the migration, which will disable Dependabot by default.
- This step was originally intended to prevent confusion due to updates after migration began, but archiving the repository will achieve the same effect once complete.
- Related conversation in Slack: [Discussion on …

chore: updating migration docs to remove dependabot step

---

apps/storybook-react/.storybook/preview.tsx
apps/storybook-react/package.json
packages/design-system-react/package.json
packages/design-system-tailwind-preset/package.json
yarn.lock

This PR updates the design tokens minor version from 4.0.0 to 4.1.0.  Since we're locked to the major version, we were already using 4.1.0, but this PR allows us to test the light/dark class names in Storybook.
Fixes: N/A 
1. Check that the design tokens library version has been updated to 4.1.0.
2. Verify that light and dark mode classnames are correctly applied and responsive to theme changes.
3. Confirm that licensing information is visible and accurate where required.
https://github.com/user-attachments/assets/cc5b8cc4-712a-41f9-8cb6-dd0bdc348408
https://github.com/user-attachments/assets/02f12f35-4129-42ad-bf28-894e83b97ccc

chore: updating design tokens package

---

merged-packages/design-tokens/package.json

This PR resolves [Issue #108](https://github.com/MetaMask/metamask-design-system/issues/108) by aligning the dependencies and build scripts in the target package with the monorepo's root configuration as part of the design tokens migration process. Following the [Package Migration Process Guide](https://github.com/MetaMask/metamask-design-system/blob/main/docs/package-migration-process-guide.md#pr10-6-align-dependencies-and-build-scripts-with-monorepo)
Fixes: https://github.com/MetaMask/metamask-design-system/issues/108
1. Verify that all unnecessary dependencies have been removed

chore: update align dependencies and update build scripts in design tokens

---

apps/storybook-react/.storybook/main.ts
apps/storybook-react/package.json
apps/storybook-react/vite.config.ts
yarn.lock

Storybook clean up removing some configuration that is no longer needed
Fixes: N/A
1. Pull this branch
2. Run `yarn storybook`
3. Check storybook runs as expected
https://github.com/user-attachments/assets/113e3ed7-ede6-4b99-817b-71e62f5b29fa

chore: storybook clean up

---

apps/storybook-react-native/.storybook/storybook.requires.js

Updates from running `yarn prettier --write .` in `main` branch
Fixes: N/A
1. On `main` run `yarn prettier --write .`
2. See updated file is the same in this PR
3. Run `yarn storybook:ios` 
4. See storybook still works
Running prettier in `main` updates this file
https://github.com/user-attachments/assets/1fac735f-8310-4808-926c-b939258e5f98
https://github.com/user-attachments/assets/a0baadde-a41d-4b36-b8d2-042a24981366
Storybook still working

chore: running prettier on main

---

packages/design-system-react/src/components/text/Text.test.tsx
packages/design-system-react/src/utils/tw-merge.test.ts
packages/design-system-react/src/utils/tw-merge.ts

This PR enhances the unit tests for the `Text` component by expanding coverage to include all prop variations and types. Additionally, it adds specific tests for the `twmerge` utility to prevent conflicts with Tailwind classnames, ensuring that styles are applied correctly without unintended overrides. These improvements aim to bolster test reliability and component resilience against styling conflicts and unexpected behavior with various prop configurations.
Fixes: https://github.com/MetaMask/metamask-design-system/issues/119
1. Run the unit tests suite to verify that all `Text` component props and variants are tested.
2. Confirm that the `twmerge` utility tests pass and correctly prevent Tailwind classname conflicts.
3. Review test output to ensure each prop and `twmerge` interaction …

chore: improving Text unit and utils tests

---

packages/design-system-react/tsconfig.build.json
tsconfig.packages.build.json

This PR updates the `tsconfig.json` configuration to exclude `test.tsx` files from the build process. 
Fixes: N/A
1. Pull this branch
2. Run `yarn build`
3. Verify that the `test.tsx`, `stories.tsx` and `stories.ts`  files are not included in the build output of `design-system-react`

chore: ignoring test tsx files and duplicate configurations

---

.depcheckrc.yml
docs/package-migration-process-guide.md
package.json
packages/design-system-react-native/package.json
packages/design-system-react-native/typedoc.json
packages/design-system-react/package.json
packages/design-system-react/typedoc.json
packages/design-system-tailwind-preset/package.json
packages/design-system-tailwind-preset/typedoc.json
packages/design-system-twrnc-preset/package.json
packages/design-tokens/package.json
scripts/create-package/package-template/package.json
scripts/create-package/package-template/typedoc.json
yarn.config.cjs
yarn.lock

Because we will be using storybook and this repos READMEs for documentation we not longer need typedoc which is left over from core. This pull request removes `typedoc` and its associated configuration files from the `design-system` monorepo. This change simplifies the repository by eliminating unused tooling and dependencies, reducing potential maintenance overhead.
Fixes: https://github.com/MetaMask/metamask-design-system/issues/134
1. Check that all `typedoc` configuration files and references (e.g., `typedoc`, `build:docs`, typedoc.json`) have been removed.
- `typedoc` dependencies and configurations present in monorepo
https://github.com/user-attachments/assets/843a7174-71dc-4a92-8d09-4d4317d986b0
- All `typedoc` references have been removed from the monorepo. …

chore: removing unused typedoc

---

packages/design-system-react/package.json
packages/design-system-react/src/components/text/README.mdx
packages/design-system-react/src/components/text/Text.constants.ts
packages/design-system-react/src/components/text/Text.stories.tsx
packages/design-system-react/src/components/text/Text.test.tsx
packages/design-system-react/src/components/text/Text.tsx
packages/design-system-react/src/components/text/Text.types.ts
yarn.lock

This PR introduces several important updates to the `Text` component in the design system react:
1. Added a new `style` prop to allow inline styles when needed for more flexible styling
2. Fixes broken text variants `BodySm` and `BodyXs` with proper responsive font sizes
3. Added the `asChild` prop to enable better component composition while maintaining styles as mentioned in [the technical spike](https://docs.google.com/document/d/1hdsxxFispA7v4-uDsbSMPVe6-Ab0tVzsSWCd4r1t-Po/edit?tab=t.0#heading=h.n13wxta3tttz)
4. Added comprehensive documentation and examples for all new features
These changes improve the component's flexibility and maintainability while maintaining its core functionality.
Fixes: https://github.com/MetaMask/metamask-design-system/issues/149
1. Go to Storybook and …

chore: fixing text variants, adding style prop and changing as to asChild

---

packages/design-system-react/scripts/create-component/ComponentName/ComponentName.stories.tsx
packages/design-system-react/scripts/create-component/ComponentName/ComponentName.tsx
packages/design-system-react/scripts/create-component/ComponentName/README.mdx
packages/design-system-react/scripts/create-component/create-component.test.ts
packages/design-system-react/scripts/create-component/create-component.ts
packages/design-system-react/src/components/text/README.mdx
packages/design-system-react/src/components/text/Text.stories.tsx

This PR improves component documentation by adding standardized code examples and consistent heading structure to react components. The changes include:
1. Added code examples to component templates showing proper import and usage patterns
2. Updated the `create-component` script to handle code example generation:
- Added `updateReadmeCodeExample` function to handle component name replacements
- Added tests to verify code example generation and structure preservation
3. Standardized documentation structure:
- Consistent heading hierarchy
- Added code examples to Text component documentation
- Updated Text stories with default args
1. Run `yarn create-component --name TestComponent --description "A test component"`
2. Verify the generated README.mdx includes:
- Code example with correct …

chore: add standardized code examples to component documentation

---

packages/design-system-react/src/components/icon/Icon.test.tsx
packages/design-system-react/src/components/icon/Icon.types.ts
packages/design-system-react/src/components/icon/README.mdx
packages/design-system-react/src/components/text/README.mdx

This PR adds `className` and `style` props to  the `Icon` component's types as well as improve docs for engineers on how to use Tailwind classnames.
Fixes: N/A
1. Go to the design system storybook
2. Navigate to the `Icon` component
3. Verify that className and style docs

feat: enhance Icon component with className overrides and style support

---

packages/design-system-react/src/components/button-secondary/ButtonSecondary.stories.tsx
packages/design-system-react/src/components/button-secondary/ButtonSecondary.test.tsx
packages/design-system-react/src/components/button-secondary/ButtonSecondary.tsx
packages/design-system-react/src/components/button-secondary/ButtonSecondary.types.ts
packages/design-system-react/src/components/button-secondary/README.mdx
packages/design-system-react/src/components/button-secondary/index.ts
packages/design-system-react/src/components/index.ts

This PR adds a new ButtonSecondary component that extends ButtonBase with primary styling. The ButtonSecondary component provides default, danger, and inverse variants while maintaining all the functionality of ButtonBase.
Key changes:
1. Added ButtonSecondary component with primary styling
2. Added support for isDanger and isInverse variants
3. Created ButtonSecondarySize alias for ButtonBaseSize
4. Added comprehensive tests and stories
5. Added full documentation with examples
Fixes: : #142 
2. Navigate to React Components/ButtonSecondary
3. Test different variants:
- Default primary button
- Danger variant (isDanger)
- Inverse variant (isInverse)
4. Verify all ButtonBase functionality works:
- Different sizes
- Full width
- Icons
- Loading state
- …

feat: add ButtonSecondary component

---

packages/design-system-react/src/components/button-base/ButtonBase.stories.tsx
packages/design-system-react/src/components/button-base/ButtonBase.test.tsx
packages/design-system-react/src/components/button-base/ButtonBase.tsx
packages/design-system-react/src/components/button-base/ButtonBase.types.ts
packages/design-system-react/src/components/button-base/README.mdx

This PR adds automatic Text component wrapping for string children in ButtonBase, improving typography consistency across all buttons and improves customization.
Key changes:
- Added `textProps` prop to customize Text component rendering
- Added automatic string children wrapping in Text component
- Updated tests to verify Text wrapping behavior
- Added documentation and stories for textProps functionality
- Changes Icon size to small
Fixes: https://github.com/MetaMask/metamask-design-system/issues/308
2. Navigate to ButtonBase component
3. See story demonstrating Text wrapping string children rendering with default Text wrapping
https://github.com/user-attachments/assets/63059e0f-ba75-4a85-93a0-b5a4577689be …

feat: Add Text component wrapping to ButtonBase

---

packages/design-system-react/src/components/button-base/ButtonBase.tsx
packages/design-system-react/src/components/button-link/ButtonLink.stories.tsx
packages/design-system-react/src/components/button-link/ButtonLink.test.tsx
packages/design-system-react/src/components/button-link/ButtonLink.tsx
packages/design-system-react/src/components/button-link/ButtonLink.types.ts
packages/design-system-react/src/components/button-link/README.mdx
packages/design-system-react/src/components/button-link/index.ts
packages/design-system-react/src/components/index.ts

Adds a new ButtonLink component that provides link-like styling while maintaining button behavior. This component extends ButtonBase with specific link-like styling and introduces a new size option 'inherit' for better text integration.
Key changes:
- Introduces ButtonLink component with link-like styling
- Adds ButtonLinkSize enum extending ButtonBaseSize with new 'inherit' option
- Implements interactive states (hover, active, disabled, loading)
- Includes comprehensive test coverage
- Provides full documentation with examples
Fixes: : #143 
1. Run Storybook locally
2. Navigate to React Components/ButtonLink
3. Test different variants:
- Default and danger variants
- All size options (Sm, Md, Lg, Inherit)
- Full width option
- With icons/accessories
4. Verify interactive states:
- Hover …

feat: add ButtonLink component

---

packages/design-tokens/src/index.ts
packages/design-tokens/src/js/index.ts

This PR reorganizes type exports in the design-tokens package to improve type organization and maintainability. It also fixes a bug in `v4.2.0` where type imports are broken likely due to the migration of the package into the monorepo and updated build package.json configuration.
Currently, type imports require long, complex paths that no longer work e.g.
```typescript
import type { ThemeColors } from '@metamask/design-tokens/dist/types/js/themes/types'
```
This PR simplifies type imports to use the package root e.g.
```typescript
import type { ThemeColors } from '@metamask/design-tokens'
```
Key changes:
- Added explicit type exports for `ThemeColors`, `ThemeShadows`, `ThemeTypography`, and `BrandColor`
- Reorganized type exports to be more centralized and intuitive
- Simplified import …

chore: exporting types from index in design tokens

---

package.json
packages/design-tokens/CHANGELOG.md
packages/design-tokens/package.json

This PR reverts version changes that were incorrectly merged, specifically:
1. Reverts the monorepo version from 2.0.0 back to 1.0.0
2. Reverts @metamask/design-tokens from 4.3.0 back to 4.2.0
3. Removes the 4.3.0 changelog entries from design-tokens
Fixes: N/A - Version reversion
1. Check package.json versions match expected values:
- Root package.json should show version 1.0.0
- design-tokens package.json should show version 4.2.0
2. Verify CHANGELOG.md in design-tokens no longer contains 4.3.0 entries
3. Verify all packages can still be built and tested successfully
N/A - Version changes only

chore: reverting release 2.0.0

---

apps/storybook-react-native/babel.config.js
packages/design-system-react-native/.eslintrc.js
packages/design-system-react-native/babel.config.js
packages/design-system-react-native/jest.config.js
packages/design-system-react-native/jest.setup.js
packages/design-system-react-native/package.json
packages/design-system-twrnc-preset/src/Theme/Theme.providers.tsx
packages/design-system-twrnc-preset/src/Theme/Theme.types.ts
packages/design-system-twrnc-preset/src/hocs/withThemeProvider.tsx
yarn.lock

This PR prepares for the upcoming `Button` component. It includes:
- Added `reanimated` dependencies and settings to both `storybook-react-native` and `design-system-react-native`
- Updated twrnc-preset to provide `colorSetList`
Fixes: #319 
1. Run `yarn storybook:ios`
2. Verify that everything is working as intended
3.
https://github.com/user-attachments/assets/8c3b321a-6afa-4da8-ae3f-e21d79d6fef5

chore: prep for Buttons - React Native

---

package.json
yarn.lock

This PR addresses a security vulnerability in the `send` package by upgrading it to version 0.19.0 or later. The current version is vulnerable to template injection that can lead to XSS attacks when passing untrusted user input to SendStream.redirect().
1. Reason for change: Security vulnerability CVE fix for template injection in the `send` package
2. Solution: Adding a resolution to enforce `send@^0.19.0` across all dependencies
Fixes: https://github.com/MetaMask/metamask-design-system/security/dependabot/7
1. Pull the branch
2. Run `yarn install` to verify the resolution is applied
3. Verify in yarn.lock that no instances of `send` package below version 0.19.0 exist
4. Run the application to ensure no regressions in functionality
Not applicable for dependency security update.

chore: fixing security vulnerability with send dependency

---

package.json
yarn.lock

This PR updates `@babel/preset-typescript` to version ^7.23.3 to address a security vulnerability identified by Dependabot. This update helps mitigate potential security risks in the dependency chain.
Fixes: https://github.com/MetaMask/metamask-design-system/security/dependabot/2
1. Pull down this branch
2. Run `yarn install` to update dependencies
3. Run `yarn build` to verify the TypeScript compilation still works
4. Run `yarn test` to ensure all tests pass with the updated dependency
Not applicable for this dependency update.

chore: fixing security vulnerability with braces dependency

---

packages/design-system-react/src/components/text/Text.test.tsx
packages/design-system-react/src/components/text/Text.tsx
packages/design-system-react/src/components/text/Text.types.ts

This PR adds support for spreading additional HTML attributes to the Text component, allowing for better component flexibility and testing capabilities. The changes include:
1. Adding spread operator support in the Text component to pass through additional props
2. Adding a test case to verify props are correctly applied to the underlying element
3. Adding data-test id
Fixes: N/A
1. Import the Text component
2. Verify that HTML attributes (like data-testid) can be passed and are applied correctly
4. Verify existing functionality continues to work as expected
N/A - Component behavior change only
HTML attributes could not be passed through to the underlying element
HTML attributes can now be passed through and applied to the underlying element

chore: spreading props in the text component for design system react

---

packages/design-system-react-native/package.json
packages/design-system-react/package.json
packages/design-system-tailwind-preset/package.json
packages/design-system-twrnc-preset/package.json
packages/design-tokens/package.json
yarn.lock

Updates the `@metamask/auto-changelog` dependency from v3.4.4 to v4.1.0 across the design system packages. This update includes several breaking changes and new features:
Key changes in v4.1.0:
- Added `--autoCategorize` flag for automatic commit categorization
- Breaking changes from v4.0.0:
- Dropped support for Node.js <18.18
- Requires `prettier@>=3.0.0` as peer dependency
- Enables Prettier formatting by default
Fixes: https://github.com/MetaMask/metamask-design-system/pull/378
1. Run `yarn changelog:update` command to verify it works with the new version
2. Verify changelog formatting is correct with the new Prettier defaults
3. Verify Node.js version compatibility (requires >=18.18)
Changelog commands still work
https://github.com/user-attachments/assets/f3d3fd2c-82dc-4a96-b3d9-851a …

chore: upgrading auto-changelog dependency

---

packages/design-system-react/src/components/button-icon/ButtonIcon.constants.ts
packages/design-system-react/src/components/button-icon/ButtonIcon.stories.tsx
packages/design-system-react/src/components/button-icon/ButtonIcon.test.tsx
packages/design-system-react/src/components/button-icon/ButtonIcon.tsx
packages/design-system-react/src/components/button-icon/ButtonIcon.types.ts
packages/design-system-react/src/components/button-icon/README.mdx
packages/design-system-react/src/components/button-icon/index.ts
packages/design-system-react/src/components/index.ts

This PR adds `ButtonIcon` component to the design system react.
Key features include:
1. Three size variants (sm, md, lg)
2. Support for floating/contained style
3. Inverse color mode for dark backgrounds
4. Built-in accessibility with required aria labels
5. Comprehensive test coverage
6. Full Storybook documentation
The component is built on top of our existing ButtonBase component and integrates with our Icon system.
Fixes: #387
2. Navigate to React Components/ButtonIcon
3. Test different configurations:
- Try all size variants (sm, md, lg)
- Toggle floating mode
- Toggle inverse mode on dark background
- Verify disabled state
- Check hover and active states
- Check controls
- Check accessibility tests
N/A - New component …

feat: adding button icon to design system react

---

packages/design-system-react/src/components/avatar-base/AvatarBase.constants.ts
packages/design-system-react/src/components/avatar-base/AvatarBase.stories.tsx
packages/design-system-react/src/components/avatar-base/AvatarBase.test.tsx
packages/design-system-react/src/components/avatar-base/AvatarBase.tsx
packages/design-system-react/src/components/avatar-base/AvatarBase.types.ts
packages/design-system-react/src/components/avatar-base/README.mdx
packages/design-system-react/src/components/avatar-base/index.ts

This PR adds the initial `AvatarBase` component to design system react. 
Key features:
1. Five size variants: xs (16px), sm (24px), md (32px), lg (40px), and xl (48px)
2. Support for different content types: text, images, and icons
3. Customizable styling through className prop using Tailwind classes
4. Built-in accessibility features through Radix UI's Slot primitive
5. Comprehensive test coverage and Storybook documentation
Fixes: #359 
1. Run Storybook locally (`yarn storybook`)
2. Navigate to React Components/AvatarBase
3. Check the docs align with component and make sense
4. Verify controls work
N/A - New component
https://github.com/user-attachments/assets/51ef4b5c-8f41-4f67-909d-cc6033a8acaf

feat: adding avatar base component to design system react

---

packages/design-system-react/src/components/avatar-base/AvatarBase.constants.ts
packages/design-system-react/src/components/avatar-base/AvatarBase.stories.tsx
packages/design-system-react/src/components/avatar-base/AvatarBase.test.tsx
packages/design-system-react/src/components/avatar-base/AvatarBase.tsx
packages/design-system-react/src/components/avatar-base/README.mdx
packages/design-system-react/src/components/index.ts

This PR updates the AvatarBase component with the following changes:
1. **Text Consistency**:
- All fallback text now uses `TextVariant.BodySm` consistently across all avatar sizes
- Removed the `AVATAR_BASE_SIZE_TO_TEXT_VARIANT_MAP` constant
- Updated tests to verify consistent text variant usage
2. **Styling Updates**:
- Added `TextColor.TextMuted` for fallback text
- Added `uppercase` class for fallback text
- Updated font weight from `Bold` to `Medium`
3. **Square Border Radius**:
- Added `AVATAR_BASE_SQUARE_BORDER_RADIUS_MAP` with specific radius values for each size
- Updated the shape logic to use the new border radius map
- Updated tests to verify the new border radius values
4. **Fallback Text Formatting**:
- Updated storybook examples to use consistent text formatting (e.g., …

chore: avatar base react fallback updates

---

packages/design-system-react/src/components/avatar-network/AvatarNetwork.stories.tsx
packages/design-system-react/src/components/avatar-network/AvatarNetwork.test.tsx
packages/design-system-react/src/components/avatar-network/AvatarNetwork.tsx
packages/design-system-react/src/components/avatar-network/AvatarNetwork.types.ts
packages/design-system-react/src/components/avatar-network/README.mdx
packages/design-system-react/src/components/avatar-network/index.ts
packages/design-system-react/src/components/index.ts

This PR adds the initial `AvatarNetwork` component to design system react 
Key features:
1. Supports image display with fallback text
2. Configurable sizes (xs, sm, md, lg, xl) with appropriate text scaling
3. Customizable styling through className and imageProps
4. Built on top of the existing AvatarBase component
5. Fully tested and documented
Fixes: #366 
1. Run Storybook and navigate to React Components/AvatarNetwork
2. Test different sizes using the size control
3. Test image display by providing a valid src URL
4. Test fallback text by removing the src URL
5. Test custom styling using className and imageProps
6. Verify accessibility by checking alt text and ARIA attributes
N/A - New component
https://github.com/user-attachments/assets/adcd3dcd-9b0d-42b8-a064-39792ded5c06

feat: adding avatar network to design system react

---

packages/design-system-react/src/components/avatar-token/AvatarToken.stories.tsx
packages/design-system-react/src/components/avatar-token/AvatarToken.test.tsx
packages/design-system-react/src/components/avatar-token/AvatarToken.tsx
packages/design-system-react/src/components/avatar-token/AvatarToken.types.ts
packages/design-system-react/src/components/avatar-token/README.mdx
packages/design-system-react/src/components/avatar-token/index.ts
packages/design-system-react/src/components/index.ts

Has a dependency on `AvatarBase` https://github.com/MetaMask/metamask-design-system/pull/390
This PR adds the new AvatarToken component to design system react
Key features:
- Displays token logos with consistent sizing and styling
- Provides fallback text display when images are unavailable
- Supports multiple size variants
- Built on top of the AvatarBase component
- Fully tested and documented
Fixes: #364
2. Navigate to React Components/AvatarToken
3. Test different component variations:
- With and without images
- Different sizes
- Fallback text behavior
- Custom className application
4. Verify responsive behavior and image handling
5. Check accessibility features (alt text, etc.)
N/A (New component) …

feat: adding avatar token to design system react

---

packages/design-system-react-native/src/components/Text/Text.stories.tsx
packages/design-system-react/src/components/text-button/TextButton.stories.tsx
packages/design-system-react/src/components/text/Text.stories.tsx

This PR updates the Storybook story naming convention across multiple components to use the `name` property instead of `storyName`. This change aligns with the latest Storybook best practices and provides a more consistent API for story definitions.
Fixes: N/A
1. Run Storybook locally
2. Navigate to the Text component stories
3. Verify that all stories appear correctly with their proper names
4. Check that the Font Weight, Font Style, Text Transform, Text Align, and Overflow Wrap stories are properly labeled
Updated stories still work as expected
https://github.com/user-attachments/assets/fa664cab-95b6-4434-99c7-589da7847701

chore: updating deprecated story name usage

---

apps/storybook-react-native/.storybook/storybook.requires.js
packages/design-system-react-native/src/components/AvatarFavicon/AvatarFavicon.constants.ts
packages/design-system-react-native/src/components/AvatarFavicon/AvatarFavicon.stories.tsx
packages/design-system-react-native/src/components/AvatarFavicon/AvatarFavicon.test.tsx
packages/design-system-react-native/src/components/AvatarFavicon/AvatarFavicon.tsx
packages/design-system-react-native/src/components/AvatarFavicon/AvatarFavicon.types.ts
packages/design-system-react-native/src/components/AvatarFavicon/README.md
packages/design-system-react-native/src/components/AvatarFavicon/index.ts
packages/design-system-react-native/src/shared/enums.ts

This PR adds the `AvatarFavicon` component to DSRN.
Fixes: #367 
2. Go to Components > AvatarFavicon
3.
https://github.com/user-attachments/assets/339dbb95-be54-472c-b2c1-3a05008c85d4

[DSRN] Added AvatarFavicon

---

packages/design-system-react/src/components/index.ts

This PR adds missing type exports to the design-system-react package's main index.ts file. During an audit of component exports, we identified that some types and enums were defined but not properly exported, which could prevent consumers from accessing these types.
Fixes: N/A
1. Import the newly exported types in a consuming project:
```typescript
import { AvatarBaseShape, ButtonIconSize } from '@metamask/design-system-react';
```
2. Verify the types are properly resolved and available
3. Verify existing type exports continue to work as expected
N/A - Type system changes only

chore: exporting missing types from index

---

package.json
yarn.lock

This PR addresses critical security vulnerabilities identified by Socket Security scanning tool, particularly focusing on the critical and high issues that aren't supply chain attacks, which we are protected against by lavamoat
Fixes: #467 
1. Go to the [Socket Report](https://socket.dev/dashboard/org/MetaMask/sbom/8cbf5ef7-aad0-4b7b-8e49-3659e293bda1?action=error%2Cmonitor%2Cwarn)
2. Check that the versions that have been updated in the resolutions section address versions with vulnerabilities  
Vulnerabilities addressed 
```
Would you like me to make any adjustments to this PR description?

fix: socket security vulnerabilities 

---

packages/design-tokens/src/css/brand-colors.css
packages/design-tokens/src/css/dark-theme-colors.css
packages/design-tokens/src/css/light-theme-colors.css
packages/design-tokens/src/figma/brandColors.json
packages/design-tokens/src/figma/darkTheme.json
packages/design-tokens/src/figma/lightTheme.json
packages/design-tokens/src/js/brandColor/brandColor.ts
packages/design-tokens/src/js/themes/darkTheme/colors.ts
packages/design-tokens/src/js/themes/lightTheme/colors.ts
packages/design-tokens/src/js/themes/types.ts

This PR updates the design tokens to align with the brand evolution "blurple" colors and fixes some casing inconsistencies introduced in #428. The changes primarily affect the blue color palette across our design system, ensuring consistency between Figma values and our implementation.
Key updates include:
1. Updating the blue color scale in brand colors from the current palette to the new "blurple" palette
2. Adjusting primary, info, and shadow colors in both light and dark themes to use the new blue values
3. Fixing casing consistency in color values to ensure they match Figma exactly
Fixes: https://github.com/MetaMask/metamask-design-system/issues/475
1. Pull the branch and build storybook `yarn storybook`
2. Verify that all blue colors have been updated to the new "blurple" palette
3. …

feat: Updating blue to brand evolution blurple

---

packages/design-system-react-native/src/primitives/Blockies/Blockies.tsx
packages/design-system-react/src/components/blockies/Blockies.stories.tsx
packages/design-system-react/src/components/blockies/Blockies.test.tsx
packages/design-system-react/src/components/blockies/Blockies.tsx
packages/design-system-react/src/components/blockies/README.mdx
packages/design-system-react/tsconfig.build.json

This PR makes some small updates to the DSR Blockies component by better aligning it with other React components in our design system and enhancing accessibility. The changes include:
1. Added default alt text for improved accessibility
2. Updated documentation to include an accessibility section
3. Added test coverage for alt text behavior
These changes make the Blockies component more consistent with our other components and improve the experience for users relying on screen readers.
Fixes: N/A
1. Go to the Blockies component in Storybook
2. Verify that the default alt text appears when inspecting the component
3. Test with a screen reader to confirm the alt text is being read
4. Override the alt text with a custom value and verify it works as expected …

Small updates to DSR/blockies

---

package.json
yarn.lock

This PR fixes a critical issue where the update to node-fetch 3.1.1 broke Expo compatibility. While version 3.1.1 was intended to address security vulnerabilities, it introduced breaking changes that make it incompatible with Expo. We can still address the security concern (CVE-2022-0235) by using version 2.6.7, which includes the necessary security patches while maintaining compatibility.
1. Reason for change: The update to node-fetch 3.1.1 broke Expo functionality
2. Solution: Revert to node-fetch 2.6.7 which:
- Maintains Expo compatibility
- Still includes patches for CVE-2022-0235 security vulnerability
- Removes breaking changes introduced in v3.x
- Fixes: Expo compatibility broken by node-fetch 3.1.1
- Maintains fix for: CVE-2022-0235 (GHSA-r683-j2x4-v87g)
1. Install dependencies …

fix: expo by downgrading dependency

---

packages/design-system-react/src/components/badge-status/BadgeStatus.constants.ts
packages/design-system-react/src/components/badge-status/BadgeStatus.stories.tsx
packages/design-system-react/src/components/badge-status/BadgeStatus.test.tsx
packages/design-system-react/src/components/badge-status/BadgeStatus.tsx
packages/design-system-react/src/components/badge-status/BadgeStatus.types.ts
packages/design-system-react/src/components/badge-status/README.mdx
packages/design-system-react/src/components/badge-status/index.ts
packages/design-system-react/src/components/index.ts

This PR adds the `BadgeStatus` component to the `@metamask/design-system-react` package
Fixes: #398 
1. Run `yarn storybook` from root
2. Go to React Components > BadgeStatus
3.
https://github.com/user-attachments/assets/5d09e373-c1cd-4304-bc03-5134b4274098

[DSR] Added BadgeStatus

---

packages/design-tokens/CHANGELOG.md
packages/design-tokens/MIGRATION.md
packages/design-tokens/src/css/typography.css
packages/design-tokens/src/figma/tokens.json
packages/design-tokens/src/js/typography/fontFamilies.ts
packages/design-tokens/stories/Typography.mdx
packages/design-tokens/stories/Typography.stories.tsx

This PR standardizes the font family name to "CentraNo1" (without space) across design tokens to align with Mobile and Extension implementations.
1. Reason for change: There was an inconsistency where Portfolio used "Centra No1" (with space) while Mobile and Extension used "CentraNo1" (without space). This inconsistency caused the design tokens to display incorrectly.
2. Improvement: Consolidates all references to use "CentraNo1" without space, matching the Mobile and Extension implementation, which fixes the font display in design tokens and ensures consistency across platforms.
Fixes: Cross-platform font family name inconsistency causing display issues in design tokens
1. Verify font family name is "CentraNo1" (without space) in:
- CSS variables (`--font-family-sans`)
- Storybook …

chore: fixing centrano1 font name in token by removing space

---

packages/design-tokens/MIGRATION.md

This PR updates the Migration Guide (v6.0.0 to v7.0.0) to include missing information and improve clarity around font family token changes. The updates include:
1. Added missing `--font-family-sans` to the list of removed CSS variables
2. Enhanced documentation of font family fallbacks in the new tokens
3. Clarified migration steps regarding the transition from `--font-family-sans` to `--font-family-default`
These changes ensure developers have complete information when migrating from v6.0.0 to v7.0.0, particularly around font family token changes.
Fixes: [Add issue number if applicable]
1. Go to the Migration Guide in `packages/design-tokens/MIGRATION.md`
2. Review the "From version 6.0.0 to 7.0.0" section
3. Verify that the removed tokens list now includes `--font-family-sans`
4. …

chore: adding missing info to design token migration docs

---

packages/design-system-react/src/components/Text/Text.stories.tsx
packages/design-system-react/src/types/index.ts

This PR adds hover and pressed states to the TextColor enum in the React design system to match the functionality already present in the React Native design system. This ensures consistency between both design systems and provides better support for interactive text states.
Fixes: #573 
1. Run Storybook for the React design system
2. Navigate to the Text component stories
3. Verify that all new hover and pressed states are visible in the Color story
Text colors didn't contain hover and pressed states
https://github.com/user-attachments/assets/12a451c4-6561-4aec-8b40-9f229ed578e5
Added hover and pressed states for all semantic colors, except info which have them at the design token level:
https://github.com/user-attachments/assets/33c3a515-a7a5-4314-a3e2-1f2af090f6cd

chore: add pressed and hover to text color type

---

packages/design-system-react/src/components/BadgeStatus/BadgeStatus.constants.ts
packages/design-system-react/src/components/BadgeStatus/BadgeStatus.tsx
packages/design-system-react/src/components/BadgeStatus/BadgeStatus.types.ts
packages/design-system-react/src/components/BadgeStatus/README.mdx
packages/design-system-react/src/types/index.ts

This PR updates the `BadgeStatus` component in the `@metamask/design-system-react` package
- Updated description to BadgeStatus indicates the state of an item through color
- Update component to remove absolute positioned background color element
- Update props status to Active (Green), Inactive (Green Border), Disconnected (Gray), New (Blue), Attention (Red)
- Update docs to add (Connected) to the Active and Inactive option for status
Fixes: #645 
1. Run `yarn storybook`
2. Check BadgeStatus
3.
https://github.com/user-attachments/assets/66e774ec-2a02-4516-a87c-e650ed63f3eb

[DSR] Aligned BadgeStatus

---

packages/design-system-react-native/src/components/BadgeStatus/BadgeStatus.constants.ts
packages/design-system-react-native/src/components/BadgeStatus/BadgeStatus.test.tsx
packages/design-system-react-native/src/components/BadgeStatus/BadgeStatus.tsx
packages/design-system-react-native/src/components/BadgeStatus/BadgeStatus.types.ts
packages/design-system-react-native/src/components/BadgeStatus/README.md
packages/design-system-react-native/src/types/index.ts

This PR updates the `BadgeStatus` component in the `@metamask/design-system-react-native` package
- Updated description to BadgeStatus indicates the state of an item through color
- Update component to remove absolute positioned background color element
- Update props status to Active (Green), Inactive (Green Border), Disconnected (Gray), New (Blue), Attention (Red)
- Update docs to add (Connected) to the Active and Inactive option for status
Fixes: #646 
1. Run `yarn storybook:ios`
2. Check BadgeStatus
3.
https://github.com/user-attachments/assets/259e36a8-b6a7-473d-b4ca-0673718f3334

[DSRN] Align BadgeStatus

---

packages/design-system-react-native/scripts/build.js

This PR fixes the React Native build script to properly include non-TypeScript files in the distribution package. The changes add two additional steps to the build process:
1. Copy Blockies utilities JavaScript files that haven't been converted to TypeScript yet
2. Copy SVG assets required by the Icon component
These additions ensure that all necessary assets are included in the final build package, preventing missing file errors when consuming the library.
Fixes: https://github.com/MetaMask/metamask-design-system/issues/652
1. Run the build script using `yarn workspace @metamask/design-system-react-native build` in root
2. Verify that the Blockies utilities are copied to `dist/components/temp-components/Blockies/`
3. Verify that SVG assets are copied to `dist/components/Icon/assets/` …

fix: broken build of DSRN

---

eslint-warning-thresholds.json
packages/design-system-react/src/components/AvatarAccount/AvatarAccount.tsx
packages/design-system-react/src/components/AvatarBase/AvatarBase.tsx
packages/design-system-react/src/components/AvatarFavicon/AvatarFavicon.tsx
packages/design-system-react/src/components/AvatarGroup/AvatarGroup.tsx
packages/design-system-react/src/components/AvatarIcon/AvatarIcon.test.tsx
packages/design-system-react/src/components/AvatarIcon/AvatarIcon.tsx
packages/design-system-react/src/components/AvatarNetwork/AvatarNetwork.tsx
packages/design-system-react/src/components/AvatarToken/AvatarToken.tsx
packages/design-system-react/src/components/BadgeCount/BadgeCount.tsx
packages/design-system-react/src/components/BadgeIcon/BadgeIcon.test.tsx
packages/design-system-react/src/components/BadgeIcon/BadgeIcon.tsx
packages/design-system-react/src/components/BadgeNetwork/BadgeNetwork.tsx
packages/design-system-react/src/components/BadgeStatus/BadgeStatus.test.tsx
packages/design-system-react/src/components/BadgeStatus/BadgeStatus.tsx
packages/design-system-react/src/components/BadgeWrapper/BadgeWrapper.tsx
packages/design-system-react/src/components/Button/Button.test.tsx
packages/design-system-react/src/components/Button/Button.tsx
packages/design-system-react/src/components/Button/variants/ButtonPrimary/ButtonPrimary.tsx
packages/design-system-react/src/components/Button/variants/ButtonSecondary/ButtonSecondary.tsx
packages/design-system-react/src/components/Button/variants/ButtonTertiary/ButtonTertiary.test.tsx
packages/design-system-react/src/components/Button/variants/ButtonTertiary/ButtonTertiary.tsx
packages/design-system-react/src/components/ButtonBase/ButtonBase.tsx
packages/design-system-react/src/components/ButtonIcon/ButtonIcon.tsx
packages/design-system-react/src/components/TextButton/TextButton.tsx

This PR fixes ESLint `import-x/no-named-as-default-member` linting errors throughout the design-system-react package by replacing all instances of `React.forwardRef` with proper named imports.
The changes include:
1. Adding `{ forwardRef }` to React import statements in all component files
2. Replacing `React.forwardRef` with `forwardRef` in component implementations
3. Similarly addressing `React.createRef` in test files by importing and using `{ createRef }`
These changes follow modern React best practices and improve code consistency across the codebase. The improvements make the code more maintainable and address the linting errors that were previously ignored or generating warnings.
A script was created to automate this process, ensuring consistent implementation across all affected …

fix: import-x/no-named-as-default-member violations dsr

---

eslint.config.mjs
packages/design-system-react/src/components/BadgeNetwork/BadgeNetwork.test.tsx
packages/design-system-react/src/components/BadgeWrapper/BadgeWrapper.test.tsx

This PR fixes linting violations in the BadgeNetwork and BadgeWrapper components in the design-system-react package by:
1. Removing ESLint ignores for these components in the config
2. Improving test assertions using `toStrictEqual` instead of `toEqual`
3. Adding proper null checks before accessing parent elements
4. Implementing proper mock functions with return values
5. Adding the unicode flag to regex for better internationalization support
6. Improving code comments and spacing
Part of: https://github.com/MetaMask/metamask-design-system/issues/657
1. Run ESLint on the project to verify no linting errors
2. Run the tests to confirm all tests still pass
3. Verify the Badge components render correctly in Storybook
Not applicable for linting fixes.

chore: fixing badge component linting

---

packages/design-tokens/src/css/dark-theme-colors.css
packages/design-tokens/src/css/light-theme-colors.css
packages/design-tokens/src/figma/darkTheme.json
packages/design-tokens/src/figma/lightTheme.json
packages/design-tokens/src/js/themes/darkTheme/colors.ts
packages/design-tokens/src/js/themes/lightTheme/colors.ts

**1. Updated `overlay.default` as below. This improvement enhances the distinction of modal/bottom sheet from the background layer in dark mode, and also keeps light mode consistent with the dark mode.**
lightTheme :
`overlay.default `: `#000000 66` --> `#3F434A 4D`
darkTheme :
`overlay.default `: `#000000 66` --> `3F434A 80`
--
**2.  Updated background color bugs in lightTheme.**
- `background.muted-hover` : `#e7ebee` --> `#EBEDF1`
- `background.alternative-hover` : `#f6f6f7` --> `#EBEDF1`
- `background.muted-pressed` : `#ebecef` -->` #E1E4EA`
- `background.alterntive-pressed` : `#ebecef` --> `#E1E4EA`
--
Fixes:
1. Go to this page...
2.
3.

overlay.default update

---

packages/design-system-react-native/src/components/Checkbox/Checkbox.stories.tsx
packages/design-system-react-native/src/components/Checkbox/Checkbox.test.tsx
packages/design-system-react-native/src/components/Checkbox/Checkbox.tsx
packages/design-system-react-native/src/components/Checkbox/Checkbox.types.ts
packages/design-system-react-native/src/components/Checkbox/README.md

This PR makes the Checkbox component fully controlled by requiring `isSelected` and `onChange` props. This change aligns with React best practices for form controls and ensures more predictable behavior.
Key improvements:
1. Remove internal state management from the Checkbox component
2. Make `isSelected` and `onChange` props required rather than optional
3. Improve TypeScript definitions for better type safety
4. Update tests to reflect the controlled component pattern
5. Enhance documentation and stories to demonstrate proper usage
Related to: #678 
1. Run the Storybook React Native app
2. Navigate to Components/Checkbox stories
3. Verify all checkboxes function correctly (toggle on/off)
4. Verify the ref example works by using the button to toggle the checkbox
5. Test disabled and …

chore: some suggested updates to Checkbox DSRN

---

.github/workflows/build-storybook-main.yml
.github/workflows/build-storybook-pr.yml

This PR adds a new GitHub Actions workflow that automatically builds and deploys Storybook previews for each pull request. When a PR is created or updated, the workflow:
1. Builds the Storybook for the PR's code
2. Uploads the build to AWS S3
3. Comments on the PR with a link to the Storybook preview
This improvement enhances our PR review process by making it easier to see component changes in context before merging. Reviewers can now directly view a working Storybook instance specific to each PR rather than having to check out and build the branch locally.
Fixes: https://github.com/MetaMask/metamask-design-system/issues/4
1. Check 📖 Storybook Preview comment on this PR goes to storybook build
No Storybook preview links were available directly from PRs. Reviewers had to either check out …

chore: storybook preview build for PRs

---

apps/storybook-react/.storybook/main.ts
apps/storybook-react/package.json
apps/storybook-react/stories/WalletHome.stories.tsx
yarn.lock

This PR adds a new WalletHome example story based on the home page redesign to the Storybook React app to:
- Showcase how various design system monorepo components can be combined in a real-world interface
- Provide a comprehensive testing environment for:
- Accessibility benchmarks and testing
- Performance benchmarks and testing
- Design and interaction testing
- Design token color updates and testing
- Animation testing
- Allow engineers and designers to evaluate components in a realistic environment
- Demonstrate proper component composition and responsive design patterns
It also includes configuration updates to ensure proper Tailwind CSS formatting across stories and components.
Part of: https://github.com/MetaMask/metamask-design-system/issues/654
1. Run the Storybook React app …

fix: dsr example wallet screen

---

apps/storybook-react-native/.storybook/main.js
apps/storybook-react-native/.storybook/storybook.requires.js
apps/storybook-react-native/stories/WalletHome.stories.tsx
packages/design-system-react-native/src/components/index.ts

This PR adds a new WalletHome example story based on the home page redesign to the Storybook React Native app to:
- Showcase how various design system monorepo components can be combined in a real-world interface
- Provide a comprehensive testing environment for:
- Accessibility benchmarks and testing
- Performance benchmarks and testing
- Design and interaction testing
- Design token color updates and testing
- Animation testing
- Allow engineers and designers to evaluate components in a realistic environment
- Demonstrate proper component composition and responsive design patterns
Part of: https://github.com/MetaMask/metamask-design-system/issues/654
1. Run the Storybook React Native app (`yarn storybook:ios`)
2. Navigate to "Examples/Wallet Home" in the sidebar
3. Verify that the …

fix: dsrn example wallet screen

---

apps/storybook-react/stories/WalletHome.stories.tsx
packages/design-system-react/src/components/Box/Box.test.tsx
packages/design-system-react/src/components/Box/Box.tsx
packages/design-system-react/src/components/Box/index.ts
packages/design-system-react/src/components/index.ts

This PR fixes the Box component's layout behavior and updates the WalletHome story to use Box components instead of HTML divs.
**What is the reason for the change?**
1. The Box component was always applying a `flex` class even when flex behavior wasn't needed, causing layout issues
2. Box enum types (BoxFlexDirection, BoxFlexWrap, etc.) were being exported as type-only exports, preventing their use as runtime values
3. The WalletHome story was using HTML divs instead of the design system's Box component
**What is the improvement/solution?**
1. Modified Box component to conditionally apply `flex` class only when `flexDirection` prop is provided
2. Fixed exports to properly export Box enums as values while keeping BoxSpacing and BoxProps as type exports
3. Converted all HTML divs in …

chore: updates to box and updating example screen

---

apps/storybook-react-native/stories/WalletHome.stories.tsx
packages/design-system-react-native/src/components/Box/index.ts
packages/design-system-react-native/src/components/index.ts

This PR fixes Box component layout behavior and updates the React Native WalletHome story to use Box components instead of native View components.
**What is the reason for the change?**
1. The Box component enums (`BoxFlexDirection`, `BoxFlexWrap`, `BoxAlignItems`, `BoxJustifyContent`) were being exported as type-only exports, preventing their use as runtime values in React Native components
2. The WalletHome story was using native View components instead of the design system's Box component, reducing consistency across the design system
3. Layout inconsistencies needed to be addressed to ensure proper flex behavior
**What is the improvement/solution?**
1. Fixed Box component exports to properly export enums as values instead of type-only exports, enabling runtime usage
2. Updated React …

chore: updating box exports and example screen for react native

---

packages/design-tokens/CHANGELOG.md
packages/design-tokens/MIGRATION.md

This PR adds missing changelog entries for PR #709 in the design tokens package. The original PR added new design tokens for monochromatic button support and fixed dark mode color specifications, but the changelog entry was left out.
**Changes made:**
1. **Added PR #709 entry** to version 8.0.0 
2. **Improved description** to properly reflect the scope of changes:
- Added new design tokens: `icon.default-hover`, `icon.default-pressed`, and `icon.inverse`
- Fixed dark mode colors for `text.alternative`, `text.muted`, `icon.alternative`, and `icon.muted`
3. **Corrected token naming** throughout the changelog to use forward slashes (e.g., `background/muted` instead of `background.muted`) for consistency with Figma and not to be mistaken for code
Fixes: N/A
1. Review the changelog entries in …

chore: adding missing PR to design tokens changelog for icon colors

---

packages/design-tokens/src/css/dark-theme-colors.css
packages/design-tokens/src/css/light-theme-colors.css
packages/design-tokens/src/figma/darkTheme.json
packages/design-tokens/src/figma/lightTheme.json
packages/design-tokens/src/js/themes/darkTheme/colors.ts
packages/design-tokens/src/js/themes/lightTheme/colors.ts

This update aligns the semantic success and warning color tokens with the latest Trade app design direction. Changes focus on shifting success colors from green to lime for clearer visual branding and refining warning colors in dark mode to ensure distinction from lime hues.
This is part 2 of 2 for trade-app-alignment. See [part 1 of 2](https://github.com/MetaMask/metamask-design-system/pull/774) for the other ticket.
🟢 Success Color Updates (Light & Dark Themes)
Purpose: Shift success tokens from green to lime for improved visual identity and consistency.
•	success-default
•	Light: green500 → lime500
•	Dark: green300 → lime100
•	success-default-hover
•	Light: #186C2C → #3D6C32
•	Dark: #59BA6F → #C9F570
•	success-default-pressed
•	Light: #114B1E → #2D5025
•	Dark: #76C688 → #D7F796
• …

[Design Token] Semantic color updates for trade-app alignment

---

packages/design-system-react/src/components/BadgeCount/README.mdx
packages/design-system-react/src/components/BadgeIcon/README.mdx
packages/design-system-react/src/components/BadgeNetwork/README.mdx
packages/design-system-react/src/components/BadgeStatus/README.mdx
packages/design-system-react/src/components/BadgeWrapper/README.mdx

This PR was initiated to isolate documentation updates for badge components. However, it also includes broader changes to the design system's Tailwind CSS integration and significant enhancements to the `Box` component.
1.  **Badge Component Documentation:** Updated `README.mdx` files for `BadgeCount`, `BadgeIcon`, `BadgeNetwork`, `BadgeStatus`, and `BadgeWrapper`.
2.  **Tailwind CSS Tooling Migration:** Switched from `prettier-plugin-tailwindcss` to `eslint-plugin-tailwindcss` for class sorting and validation, affecting configuration files and best practices documentation.
3.  **`Box` Component Expansion:** Added new props to the `Box` component for direct control over `margin`, `padding`, `borderWidth`, `borderColor`, and `backgroundColor`, complete with updated types, constants, …

chore: aligning badge docs

---

apps/storybook-react-native/tailwind-intellisense.config.js
eslint.config.mjs
packages/design-system-react-native/src/components/AvatarBase/AvatarBase.test.tsx
packages/design-system-react-native/src/components/BadgeIcon/BadgeIcon.test.tsx
packages/design-system-react-native/src/components/Box/Box.test.tsx
packages/design-system-react-native/src/components/Box/Box.tsx
packages/design-system-react-native/src/components/ButtonIcon/ButtonIcon.test.tsx
packages/design-system-react-native/src/components/Checkbox/Checkbox.test.tsx
packages/design-system-react-native/src/components/Checkbox/Checkbox.tsx
packages/design-system-react-native/src/components/TextButton/TextButton.test.tsx
packages/design-system-react-native/src/components/TextButton/TextButton.tsx
packages/design-system-twrnc-preset/README.md
packages/design-system-twrnc-preset/package.json
packages/design-system-twrnc-preset/src/index.ts
packages/design-system-twrnc-preset/src/tailwind.config.ts
yarn.lock

This PR significantly enhances the React Native developer experience by adding comprehensive Tailwind IntelliSense and ESLint support to the `@metamask/design-system-twrnc-preset` package. This bridges the gap between TWRNC usage and standard Tailwind tooling, providing React Native developers with the same excellent developer experience as React Web developers.
**What is the reason for the change?**
React Native developers using TWRNC were missing critical developer experience features:
- No IntelliSense/autocomplete for design system classes
- No ESLint validation of Tailwind classnames  
- No detection of invalid classes, ordering issues, or shorthand suggestions
- Difficult discovery of available design system tokens
- Manual enforcement of design system color usage
**What is the …

chore: improve tailwind intellisense and linting for react native

---

packages/design-system-react-native/src/components/AvatarAccount/AvatarAccount.tsx
packages/design-system-react-native/src/components/temp-components/Jazzicon/Jazzicon.test.tsx
packages/design-system-react-native/src/components/temp-components/Jazzicon/Jazzicon.tsx
packages/design-system-react/src/components/AvatarAccount/AvatarAccount.tsx
packages/design-system-react/src/components/temp-components/Jazzicon/Jazzicon.tsx

Updates the AvatarAccount component shape from circular to square across both React and React Native implementations. This change ensures visual consistency in the avatar display pattern and aligns with updated design system requirements for account avatars.
Fixes: N/A
1. Go to Storybook for AvatarAccount component in both React and React Native apps
2. Verify that all AvatarAccount instances now render with square shape instead of circular
3. Test different sizes (xs, sm, md, lg, xl) to ensure square shape is applied consistently
4. Verify that the component maintains proper accessibility attributes
5. Check that existing props and functionality remain unchanged (only shape has changed)
Screenshots would be helpful to visualize the shape change from circular to square avatars.

chore: update AvatarAccount shape from circle to square

---

packages/design-system-react-native/src/components/Button/Button.test.tsx
packages/design-system-react-native/src/components/Button/Button.tsx
packages/design-system-react-native/src/components/Button/Button.types.ts

Makes the `variant` prop optional for the Button component in React Native, defaulting to `ButtonVariant.Primary` when not specified. This change improves developer experience by allowing simpler Button usage without explicitly defining the variant for primary buttons, which is the most common use case.
Fixes: N/A
1. Navigate to the React Native Button component in Storybook
2. Test that Button renders with primary variant when no variant prop is provided
3. Verify that explicitly setting variant prop still works for all variants (Primary, Secondary, Tertiary)
4. Run the Button component tests to ensure all test cases pass
Button component required explicit variant prop:
```tsx
<Button variant={ButtonVariant.Primary}>Click me</Button>
```
Button component now works without variant prop …

fix: make Button variant prop optional with Primary as default

---

packages/design-system-react-native/src/components/Box/index.ts
packages/design-system-react-native/src/components/index.ts

Fixes missing type exports for the Box component in React Native. This change adds `BoxBackgroundColor` and `BoxBorderColor` enum exports to ensure complete type availability for consumers of the design system package. These enums were already available internally but not exposed through the public API, which could cause TypeScript errors when trying to use strongly-typed color props with the Box component.
Fixes: 
1. Import the Box component from `@metamask/design-system-react-native`
2. Verify that `BoxBackgroundColor` and `BoxBorderColor` enums are now available for import
3. Use these enums to set backgroundColor and borderColor props on Box components
4. Confirm TypeScript correctly validates the enum values without errors

fix: export missing Box component color enums for React Native

---

packages/design-system-shared/package.json
packages/design-system-shared/src/index.test.ts
packages/design-system-shared/src/index.ts
packages/design-system-shared/src/utils/caip-address.test.ts
packages/design-system-shared/src/utils/caip-address.ts
yarn.lock

Adds CAIP-10 address utilities to the design-system-shared package to enable consistent icon generation across different blockchain address formats. This foundational change provides utilities for extracting account addresses from CAIP-10 formatted strings and generating appropriate seeds for icon generation based on address type (Ethereum vs non-Ethereum).
The utilities support seamless handling of both legacy addresses (e.g., `0x...`) and CAIP-10 formatted addresses (e.g., `eip155:1:0x...`), ensuring the same address generates identical icons regardless of format.
Fixes: 
1. Install dependencies: `yarn install`
2. Build the shared package: `yarn workspace @metamask/design-system-shared build`
3. Run tests to verify functionality: `yarn workspace @metamask/design-system-shared test`
4. …

feat: add CAIP-10 address utilities to design-system-shared

---

packages/design-system-react/src/components/AvatarBase/AvatarBase.tsx

Fixes bug with Avatar components where they would shrink in a flex layout.
Fixes: https://github.com/MetaMask/metamask-extension/pull/35711
1. Go storybook build of this PR
2. Visit the example wallet screen
3. Use dev tools to make account name really long until it truncates
4. See that avatar remains the same size and doesn't shrink

fix: avatar shrinking in flex layouts

---

packages/design-system-react/CHANGELOG.md
packages/design-system-react/src/components/AvatarBase/AvatarBase.tsx

This PR corrects the changelog entries to accurately reflect what was shipped in each release and includes a fix for Avatar components shrinking in flex layouts. The avatar flex layout issue was merged into release/14 (v0.4.0) when main was merged but the changelogs were not updated, so the changelog has been updated to reflect the actual shipping timeline. Additionally, this includes the technical fix that changes the CSS class from `flex-shrink-0` to `shrink-0` in the AvatarBase component. Both classnames work but `shrink-0` is more accurate and aligns with [tailwind docs](https://tailwindcss.com/docs/flex-shrink)
Fixes: N/A
1. Pull and build the branch locally
2. Verify the changelog entries now accurately reflect release contents:
- v0.4.0 should include the avatar flex layout fix …

fix: correct changelog entries and avatar flex layout shrinking

---

yarn.config.cjs

Fixes peer dependency constraints for pre-1.0 packages in the monorepo. The previous implementation only used major version ranges (`^0.0.0` for all pre-1.0 packages), which was too permissive and could allow incompatible older versions. This update ensures peer dependencies correctly reflect the most significant version digit for breaking changes, following semantic versioning best practices for pre-1.0 packages.
[Same PR in core](https://github.com/MetaMask/core/pull/6652/files#diff-594447fef9feecf11f1839e337c464b7b857fdb73fde7e18940eaa9cdf5b819d)
Fixes: 
1. Run `yarn constraints` to verify no constraint violations
2. Check that the updated logic handles various version scenarios:
- `0.4.1` → generates `^0.4.0` peer dependency range
- `0.2.1` → generates `^0.2.0` peer dependency range
- …

fix: ensure peer dependencies reflect latest breaking changes for pre-1.0 packages
