MetaMask/metamask-design-system

README.md, packages/design-system-tailwind-preset/CHANGELOG.md, packages/design-system-tailwind-preset/LICENSE, packages/design-system-tailwind-preset/README.md, packages/design-system-tailwind-preset/jest.config.js, packages/design-system-tailwind-preset/package.json, packages/design-system-tailwind-preset/src/index.test.ts, packages/design-system-tailwind-preset/src/index.ts, packages/design-system-tailwind-preset/tsconfig.build.json, packages/design-system-tailwind-preset/tsconfig.json, packages/design-system-tailwind-preset/typedoc.json, tsconfig.build.json, tsconfig.json, yarn.lock
This PR creates the initial `@metamask/design-system-tailwind-preset` package using the `create-package` script. It sets up the necessary structure and dependencies for the package.
Partially fixes: https://github.com/MetaMask/metamask-design-system/issues/34
1. Navigate to the package directory.
2. Verify the contents of the README file.
3. Check the `package.json` to ensure consistent naming of the package.
- https://github.com/MetaMask/metamask-design-system/pull/41
=> Initial tailwind preset package from create-package script

apps/storybook-react-native/.storybook/storybook.requires.js, apps/storybook-react-native/README.md, apps/storybook-react/README.md, package.json
This PR updates the `storybook-react-native` README from framworkless instructions to include guidance on configuring and using it with Expo. It also adds scripts the root package.json for ease of use.
Fixes: [MetaMask Design System Issue #82](https://github.com/MetaMask/metamask-design-system/issues/82)
1. Follow the new Expo setup instructions in `README.md`.
2. Verify that Storybook runs successfully within an Expo environment.
3. Test the steps on both iOS and Android to confirm consistency across platforms.
https://github.com/user-attachments/assets/a82c0f36-920b-4f41-aa86-232033bccdc5
=> chore: updating readme for storybook

README.md, packages/design-system-twrnc-preset/CHANGELOG.md, packages/design-system-twrnc-preset/LICENSE, packages/design-system-twrnc-preset/README.md, packages/design-system-twrnc-preset/jest.config.js, packages/design-system-twrnc-preset/package.json, packages/design-system-twrnc-preset/src/index.test.ts, packages/design-system-twrnc-preset/src/index.ts, packages/design-system-twrnc-preset/tsconfig.build.json, packages/design-system-twrnc-preset/tsconfig.json, packages/design-system-twrnc-preset/typedoc.json, tsconfig.build.json, tsconfig.json, yarn.lock
This PR initiates `design-system-twrnc-preset` package using `create-package`
Fixes: #97 
1. N/A
2.
3.
=> Initiate ds-twrnc-preset package

.github/workflows/publish-preview.yml, package.json
This reverts commit eb8d1f15cbb690b80850c3928e43555987a4cc42.
https://github.com/MetaMask/metamask-design-system/issues/102 has been reopened
=> Revert "fix: publish preview builds (#121)"

packages/design-tokens/stories/Shadows.mdx, packages/design-tokens/stories/Typography.mdx
This PR fixes the broken tables for shadows and typography in the design token stories. These tables were improperly rendered, impacting the visual representation and usability of the documentation. The fix ensures that tables are displayed correctly and match the intended design specifications.
Part of https://github.com/MetaMask/metamask-design-system/issues/129
1. Pull this branch
2. Run `yarn storybook`
3. Navigate to the design token stories for shadow and typograpgy
5. Confirm that the tables render correctly and are visually consistent.
https://github.com/user-attachments/assets/7fff03bc-dbf4-42ff-84f5-ad6fd4660cbd
https://github.com/user-attachments/assets/f6ebed80-8803-4539-b9a1-07c4a4e426a5
=> chore: design token storybook fixes

packages/design-tokens/stories/test-utils/getCSSVariablesFromStylesheet.ts
This PR addresses issues in the design token storybook related to rendering CSS variables for brand color, and light and dark theme colors. Previously, the function responsible for rendering these variables was updated to comply with ESLint rules for the design system monorepo. However, because Storybook is not a Node.js environment, the updates failed to function as intended. This issue was missed during migration PRs and was my oversight.
This PR:
1. Reverts the function to its previous implementation to restore compatibility with Storybook.
2. Improves the function to better align with the upcoming improvements in the Storybook environment as outlined in [[PR #147](https://github.com/MetaMask/metamask-design-system/pull/147)](https://github.com/MetaMask/metamask-design-system/pull/147). …
=> chore: fixes get css variables from stylesheet utility

README.md
This PR updates the `README.md` to include the `design-tokens` package. Additionally, the dependency graph in the README is regenerated by running `yarn update-readme-content`, ensuring the new package is accurately reflected.
[Follows migration steps](https://github.com/MetaMask/metamask-design-system/blob/main/docs/package-migration-process-guide.md)
Fixes: N/A
1. Pull the branch and run `yarn update-readme-content` locally.
2. Verify that the `design-tokens` package is listed under the packages section of the `README.md`.
3. Confirm that the dependency graph is updated to include the new package.
*Current README content and dependency graph.*
*Updated README content reflecting the new package.*
=> chore: add design-tokens package to README and dependency graph

package.json, packages/design-system-react-native/package.json, packages/design-system-react-native/tsconfig.build.json, packages/design-system-react/package.json, packages/design-system-tailwind-preset/package.json, packages/design-system-twrnc-preset/tsconfig.build.json, packages/design-tokens/package.json, scripts/prepare-preview-builds.jq, tsconfig.build.json, yarn.lock
This PR improves the build system across the monorepo to properly handle individual package build scripts and ensure consistent building behavior.
Key improvements:
1. Updates root build script to use Yarn workspaces for better package management
2. Ensures CSS files are properly built and placed in dist directories
3. Fixes issues with individual package builds using `yarn workspace`
4. Standardizes build scripts across packages
Fixes: https://github.com/MetaMask/metamask-design-system/issues/262
1. Clean all builds: `yarn build:clean`
2. Run root build: `yarn build`
3. Run build types: `yarn build:types`
4. Verify CSS files are present in design-tokens/dist
5. Test individual package build: `yarn workspace @metamask/design-tokens run build`
6. Verify all build artifacts are generated …
=> fix: build system improvements for package-level scripts

apps/storybook-react-native/.storybook/storybook.requires.js, packages/design-system-react/src/components/icon/Icon.constants.ts, packages/design-system-react/src/components/icon/Icon.stories.tsx, packages/design-system-react/src/components/icon/Icon.test.tsx, packages/design-system-react/src/components/icon/Icon.tsx, packages/design-system-react/src/components/icon/Icon.types.ts, packages/design-system-react/src/components/icon/README.mdx, packages/design-system-react/src/components/icon/index.ts, packages/design-system-react/src/components/index.ts, packages/design-tokens/stories/Typography.stories.tsx
This pull request introduces the initial `Icon` component in the `design-system-react` package.
This PR includes:
- Creation of the `Icon` component with a focus on defining a robust component architecture.
- Comprehensive Storybook setup:
- Controls to dynamically adjust component properties.
- MDX documentation for usage guidance.
- 100% unit test coverage
- Export of the `Icon` component and its types from the `design-system-react` package.
This is an **initial implementation**, introducing one SVG asset to validate the prop architecture and foundational functionality. Future PRs will automate the inclusion of SVG icons and expand the available asset library. For more details, see the full draft PR: https://github.com/MetaMask/metamask-design-system/pull/199
Part of: …
=> feat: initial icon component that renders a basic svg

packages/design-system-tailwind-preset/src/colors.ts, packages/design-tokens/src/css/dark-theme-colors.css, packages/design-tokens/src/css/light-theme-colors.css, packages/design-tokens/src/figma/darkTheme.json, packages/design-tokens/src/figma/lightTheme.json, packages/design-tokens/src/js/themes/darkTheme/colors.ts, packages/design-tokens/src/js/themes/lightTheme/colors.ts, packages/design-tokens/src/js/themes/types.ts
Added 8 new colors (16 values total for light & dark themes) to the Figma JSON.
```
<LIGHT THEME>
metamask-design-system/packages/design-tokens/src/figma/lighTheme.json
Primary
- muted-hover : #0376c926
- muted-pressed : #0376c933
Error
- muted-hover : #d7384726
- muted-pressed : #d7384733
Warning
- muted-hover : #bf520826
- muted-pressed : #bf520833
Success
- muted-hover : #1c823426
- muted-pressed : #1c823433
```
```
<DARK THEME>
metamask-design-system/packages/design-tokens/src/figma/darkTheme.json
Primary
- muted-hover : #43aefc33
- muted-pressed : #43aefc40
Error
- muted-hover : #e88f9733
- muted-pressed : #e88f9740
Warning
- muted-hover : #ffdf7033
- muted-pressed : #ffdf7040
Success
- muted-hover : #28a74533
- muted-pressed : #28a74540
```
Fixes: #321 
1. Go to this page...
2.
3.
=> Added 8 new colors (4 muted-hover & 4 muted-pressed) to design-tokens Figma Json.

apps/storybook-react-native/.storybook/storybook.requires.js, packages/design-system-react-native/src/README.md, packages/design-system-react-native/src/components/Text/index.ts, packages/design-system-react-native/src/temp-components/Spinner/README.md, packages/design-system-react-native/src/temp-components/Spinner/Spinner.constants.ts, packages/design-system-react-native/src/temp-components/Spinner/Spinner.stories.tsx, packages/design-system-react-native/src/temp-components/Spinner/Spinner.test.tsx, packages/design-system-react-native/src/temp-components/Spinner/Spinner.tsx, packages/design-system-react-native/src/temp-components/Spinner/Spinner.types.ts, packages/design-system-react-native/src/temp-components/Spinner/index.ts
- This PR adds `Spinner` temp component
Fixes: #354 
2. Go to Temp Components > Spinner
3.
https://github.com/user-attachments/assets/d287eb7c-8afd-47f2-a882-59d0e665be0c
=> [React Native] Added spinner component

packages/design-system-react/src/components/button-base/ButtonBase.stories.tsx, packages/design-system-react/src/components/button-base/ButtonBase.test.tsx, packages/design-system-react/src/components/button-base/ButtonBase.tsx, packages/design-system-react/src/components/button-base/ButtonBase.types.ts, packages/design-system-react/src/components/button-base/README.mdx, packages/design-system-react/src/components/button-primary/ButtonPrimary.stories.tsx, packages/design-system-react/src/components/button-primary/ButtonPrimary.test.tsx, packages/design-system-react/src/components/button-primary/ButtonPrimary.tsx, packages/design-system-react/src/components/button-primary/README.mdx, packages/design-system-react/src/components/button-secondary/ButtonSecondary.stories.tsx, packages/design-system-react/src/components/button-secondary/ButtonSecondary.test.tsx, packages/design-system-react/src/components/button-secondary/ButtonSecondary.tsx, packages/design-system-react/src/components/button-secondary/README.mdx, packages/design-system-react/src/components/button-tertiary/ButtonTertiary.stories.tsx, packages/design-system-react/src/components/button-tertiary/ButtonTertiary.test.tsx, packages/design-system-react/src/components/button-tertiary/ButtonTertiary.tsx, packages/design-system-react/src/components/button-tertiary/ButtonTertiary.types.ts, packages/design-system-react/src/components/button-tertiary/README.mdx
This PR updates all button components (Base, Primary, Secondary, and Tertiary) to align with the latest Figma designs, focusing on consistent interaction states and variant combinations. Key changes include:
1. **Unified Scale Animation**
- Standardized scale animation to 0.98 across all button types
- Updated animation timing function to cubic-bezier(0.3,0.8,0.3,1)
- Consolidated transition properties for transform, colors, and opacity
2. **Loading State Improvements**
- Loading states now use pressed background colors
- Maintained button content visibility during loading (invisible vs removed)
- Removed opacity reduction during loading to maintain visual hierarchy
3. **Variant Consistency**
- Aligned danger and inverse styles across all button types
- Updated hover/active state …
=> chore: updating button styles to align with Figma

packages/design-system-react-native/src/temp-components/Spinner/README.md, packages/design-system-react-native/src/temp-components/Spinner/Spinner.constants.ts, packages/design-system-react-native/src/temp-components/Spinner/Spinner.stories.tsx, packages/design-system-react-native/src/temp-components/Spinner/Spinner.types.ts, packages/design-system-react-native/src/temp-components/Spinner/index.ts
This PR fixes a circular dependency issue in the Spinner component by directly using IconColor instead of re-exporting it as SpinnerColor. The change simplifies the component's dependency structure and follows best practices for type imports.
1. Reason for change: Remove circular dependency that was causing potential build and runtime issues
2. Solution: Import IconColor directly from the Icon component instead of re-exporting it through the Spinner index
Changes include:
- Removed SpinnerColor import from index
- Directly imported IconColor from Icon component
- Updated DEFAULT_SPINNER_PROPS to use IconColor instead of SpinnerColor
Fixes: N/A
1. Pull down this branch
2. Run `yarn storybook:ios`
3. Build the project and verify no circular dependency warnings
4. Test the Spinner component …
=> chore: fixing circular dependency issue in spinner

packages/design-system-react/src/components/button/Button.stories.tsx, packages/design-system-react/src/components/button/Button.test.tsx, packages/design-system-react/src/components/button/Button.tsx, packages/design-system-react/src/components/button/Button.types.ts, packages/design-system-react/src/components/button/README.mdx, packages/design-system-react/src/components/button/index.ts, packages/design-system-react/src/components/index.ts
This PR unifies the separate button variants (Primary, Secondary, Tertiary) into a single Button component for better maintainability and consistent API.
Fixes: #144
2. Navigate to the Button component
3. Test all variants (Primary, Secondary, Tertiary)
4. Verify all features work across variants:
- Sizes
- Icons
- Loading states
- Disabled states
- Danger variants
- Inverse variants
- Danger + Inverse variants (all the same style)
https://github.com/user-attachments/assets/2d84c046-74a9-49e7-83b2-76ac58bf93c0
=> feat: adding Button component

packages/design-system-react/src/components/avatar-icon/AvatarIcon.constants.ts, packages/design-system-react/src/components/avatar-icon/AvatarIcon.stories.tsx, packages/design-system-react/src/components/avatar-icon/AvatarIcon.test.tsx, packages/design-system-react/src/components/avatar-icon/AvatarIcon.tsx, packages/design-system-react/src/components/avatar-icon/AvatarIcon.types.ts, packages/design-system-react/src/components/avatar-icon/README.mdx, packages/design-system-react/src/components/avatar-icon/index.ts, packages/design-system-react/src/components/index.ts
This PR adds `AvatarIcon` to design system react
- Five predefined sizes (Xs, Sm, Md, Lg, Xl) with corresponding icon sizes
- Five severity levels (Default, Info, Success, Error, Warning) with appropriate background and icon colors
- Customizable icon properties and additional className support
- Comprehensive Storybook documentation and test coverage
The component is built on top of the existing `AvatarBase` and `Icon` components, ensuring consistency with the design system.
Fixes: #370 
1. Go to Storybook and navigate to the AvatarIcon component
2. Test different icon names using the IconName story
3. Verify all size variations in the Size story
4. Check all severity levels in the Severity story
5. Test custom className and iconProps functionality
N/A (New component) …
=> feat: adding avatar icon to design system react

packages/design-system-react/src/components/avatar-base/AvatarBase.stories.tsx, packages/design-system-react/src/components/avatar-base/AvatarBase.tsx, packages/design-system-react/src/components/avatar-favicon/AvatarFavicon.test.tsx, packages/design-system-react/src/components/avatar-network/AvatarNetwork.test.tsx, packages/design-system-react/src/components/avatar-token/AvatarToken.test.tsx, packages/design-system-react/src/components/button-base/ButtonBase.stories.tsx, packages/design-system-react/src/components/button-base/ButtonBase.test.tsx, packages/design-system-react/src/components/button-base/ButtonBase.tsx, packages/design-system-react/src/components/button-icon/ButtonIcon.stories.tsx, packages/design-system-react/src/components/button-icon/ButtonIcon.test.tsx, packages/design-system-react/src/components/button-primary/ButtonPrimary.stories.tsx, packages/design-system-react/src/components/button-primary/ButtonPrimary.test.tsx, packages/design-system-react/src/components/button-secondary/ButtonSecondary.stories.tsx, packages/design-system-react/src/components/button-secondary/ButtonSecondary.test.tsx, packages/design-system-react/src/components/button-tertiary/ButtonTertiary.stories.tsx, packages/design-system-react/src/components/button-tertiary/ButtonTertiary.test.tsx, packages/design-system-react/src/components/button/Button.stories.tsx, packages/design-system-react/src/components/button/Button.test.tsx, packages/design-system-react/src/components/button/Button.tsx, packages/design-system-react/src/components/text-button/TextButton.stories.tsx, packages/design-system-react/src/components/text-button/TextButton.test.tsx
This PR addresses the first part of circular dependency issues by fixing import paths across multiple components. Instead of using barrel imports (`'..'`), we now directly import from specific component files. This change:
1. Removes circular dependencies caused by barrel imports
2. Makes the import structure more explicit and maintainable
3. Prepares the codebase for further circular dependency fixes
This update is very similar to the one implemented in the MetaMask extension, which can be referenced here: [MetaMask Extension PR #30267](https://github.com/MetaMask/metamask-extension/pull/30267). That PR also focused on updating import paths in the `component-library` folder to resolve circular dependencies.
The changes primarily affect:
- Avatar components (Base, Favicon, Network, Token) …
=> chore: removing circular dependencies from imports

apps/storybook-react-native/.storybook/storybook.requires.js, packages/design-system-react-native/src/components/TextButton/TextButton.tsx, packages/design-system-react-native/src/index.ts, packages/design-system-react-native/src/primitives/AvatarBase/AvatarBase.constants.ts, packages/design-system-react-native/src/primitives/AvatarBase/AvatarBase.stories.tsx, packages/design-system-react-native/src/primitives/AvatarBase/AvatarBase.test.tsx, packages/design-system-react-native/src/primitives/AvatarBase/AvatarBase.tsx, packages/design-system-react-native/src/primitives/AvatarBase/AvatarBase.types.ts, packages/design-system-react-native/src/primitives/AvatarBase/AvatarBase.utilities.ts, packages/design-system-react-native/src/primitives/AvatarBase/README.md, packages/design-system-react-native/src/primitives/AvatarBase/index.ts, packages/design-system-react-native/src/shared/enums.ts
This PR adds the `AvatarBase` component to the `design-system-react-native` package
Fixes: #357 
2. Go to Primitives > AvatarBase
3.
https://github.com/user-attachments/assets/61def6f5-26c0-4b77-955b-08233d5a144e
=> [DSRN]Added AvatarBase

apps/storybook-react-native/.storybook/storybook.requires.js, packages/design-system-react-native/src/components/AvatarFavicon/README.md, packages/design-system-react-native/src/components/AvatarToken/AvatarToken.constants.ts, packages/design-system-react-native/src/components/AvatarToken/AvatarToken.stories.tsx, packages/design-system-react-native/src/components/AvatarToken/AvatarToken.test.tsx, packages/design-system-react-native/src/components/AvatarToken/AvatarToken.tsx, packages/design-system-react-native/src/components/AvatarToken/AvatarToken.types.ts, packages/design-system-react-native/src/components/AvatarToken/README.md, packages/design-system-react-native/src/components/AvatarToken/index.ts, packages/design-system-react-native/src/index.ts, packages/design-system-react-native/src/shared/enums.ts
This PR adds the `AvatarToken` component to the DSRN
Fixes: #363 
2. Go to Components > AvatarToken
3.
https://github.com/user-attachments/assets/0a673f9e-42c5-49c0-a2e0-fc3ef7295cae
=> [DSRN] Added AvatarToken

.github/workflows/ensure-blocking-pr-labels-absent.yml, .github/workflows/lint-build-test.yml, .github/workflows/main.yml, .github/workflows/publish-preview.yml, .github/workflows/publish-release.yml, .github/workflows/security-code-scanner.yml
This updates all workflows to remove the use of `actions/checkout`, `actions/setup-node`, `actions/cache`. The implementation here is based on https://github.com/MetaMask/core/pull/5474
Key improvements:
1. Replaces manual Node.js setup and caching with a standardized action
2. Adds proper high-risk environment handling for sensitive workflows
3. Updates Node.js version matrix to include v22.x
4. Improves security by removing potentially vulnerable caching mechanisms
Fixes: https://github.com/MetaMask/metamask-design-system/issues/377
- https://github.com/MetaMask/metamask-design-system/security/code-scanning/3
- https://github.com/MetaMask/metamask-design-system/security/code-scanning/2
- https://github.com/MetaMask/metamask-design-system/security/code-scanning/1
1. Review the changes …
=> chore: Update workflows to use MetaMask/action-checkout-and-setup

packages/design-system-react-native/src/components/BadgeIcon/BadgeIcon.types.ts, packages/design-system-react/src/components/badge-icon/BadgeIcon.stories.tsx, packages/design-system-react/src/components/badge-icon/BadgeIcon.test.tsx, packages/design-system-react/src/components/badge-icon/BadgeIcon.tsx, packages/design-system-react/src/components/badge-icon/BadgeIcon.types.ts, packages/design-system-react/src/components/badge-icon/README.mdx, packages/design-system-react/src/components/badge-icon/index.ts, packages/design-system-react/src/components/index.ts
This PR adds the `BadgeIcon` to the `@metamask/design-system-react` package
Fixes: #402 
1. Run `yarn storybook` from root
2. Go to React Components > Badge Icon
3.
https://github.com/user-attachments/assets/afa99c62-f8cc-4d54-9321-db9f6835529d
=> [DSR] Added BadgeIcon

packages/design-system-react-native/src/components/Text/README.md, packages/design-system-react-native/src/components/Text/Text.constants.ts, packages/design-system-react-native/src/components/Text/Text.stories.tsx, packages/design-system-react-native/src/components/Text/Text.tsx, packages/design-system-react-native/src/components/Text/Text.types.ts, packages/design-system-react-native/src/components/Text/Text.utilities.ts, packages/design-system-react-native/src/primitives/TextOrChildren/TextOrChildren.stories.tsx, packages/design-system-react/src/components/text/README.mdx, packages/design-system-react/src/components/text/Text.constants.ts, packages/design-system-react/src/components/text/Text.stories.tsx, packages/design-system-react/src/components/text/Text.test.tsx, packages/design-system-react/src/components/text/Text.tsx, packages/design-system-react/src/components/text/Text.types.ts, packages/design-system-tailwind-preset/src/typography.test.ts, packages/design-system-tailwind-preset/src/typography.ts, packages/design-tokens/src/figma/tokens.json, packages/design-tokens/src/js/typography/fontSizes.test.ts, packages/design-tokens/src/js/typography/fontSizes.ts, packages/design-tokens/src/js/typography/fontWeights.test.ts, packages/design-tokens/src/js/typography/fontWeights.ts, packages/design-tokens/src/js/typography/letterSpacing.ts, packages/design-tokens/src/js/typography/lineHeights.test.ts, packages/design-tokens/src/js/typography/lineHeights.ts, packages/design-tokens/src/js/typography/types.ts, packages/design-tokens/stories/Typography.stories.tsx, packages/design-tokens/tsconfig.json
This PR improves Quality of Life for Typography in Monorepo
- add types to typescript variables FontSize, LineHeight, FontWeight, LetterSpacing to @metamask/design-tokens package
- align FontSize and LineHeight across figma, css, and js to @metamask/design-tokens package
- Updated FontWeight Normal enum in the Text component to Regular in both the @metamask/design-system-react and @metamask/design-system-react-native packages
- Fix Typography stories error in @metamask/design-tokens package 
Fixes: #528 
1. Run `yarn storybook:ios` or `yarn storybook` from root
2. Check the Text component to make sure everything is functional
3.
https://github.com/user-attachments/assets/d0811228-0446-405f-b0c4-3de36ce3e433
https://github.com/user-attachments/assets/bc7bcbb5-dc2c-4daa-a94d-7ed5cf8b5844
=> Improve Quality of Life for Typography in Monorepo

packages/design-system-react-native/src/components/Text/README.md
This PR simplifies the Text component description in the README.md file to be more concise and aligned with DSR and Figma
Fixes: #575 
1. Navigate to the Text component documentation
2. Confirm that the new description is clear and concise
=> chore: align descriptions for text component

packages/design-system-react-native/src/components/BadgeNetwork/BadgeNetwork.stories.tsx
This PR updated the `BadgeNetwork` stories in `@metamask/design-system-react-native` to use the correct src. 
Fixes: #579 
2. Go to Components > BadgeNetwork
3.
https://github.com/user-attachments/assets/f705f27e-463b-4132-8851-661f6507bf31
=> [DSRN] Updated BadgeNetwork stories to use the correct src

.prettierrc.js, apps/storybook-react/tailwind.config.js, packages/design-system-react/src/components/Button/variants/ButtonSecondary/ButtonSecondary.tsx, packages/design-system-react/src/components/ButtonBase/ButtonBase.tsx, packages/design-system-react/src/components/ButtonIcon/ButtonIcon.tsx, packages/design-system-react/src/components/Icon/Icon.test.tsx, packages/design-system-react/src/components/TextButton/TextButton.tsx, packages/design-tokens/stories/Shadows.stories.tsx
This PR standardizes Tailwind CSS class ordering across the design system and improves Tailwind configuration for component libraries. It ensures consistent class ordering patterns while expanding configuration coverage to include story files in both React and React Native environments.
Key changes:
- Expanded Tailwind configuration coverage to include story files in both React and React Native environments
- Standardized class ordering in button components and various other UI elements
- Modified storybook-react Tailwind config to rely exclusively on colors from the design system preset
Fixes: N/A
1. Run the storybook applications to ensure components render correctly
2. Verify that all components maintain their styling and appearance
3. Check that Prettier formatting works properly with …
=> chore: updates to tailwind prettier configuration

apps/storybook-react-native/.storybook/storybook.requires.js, apps/storybook-react-native/package.json, packages/design-system-react-native/jest.config.js, packages/design-system-react-native/jest.setup.js, packages/design-system-react-native/src/components/Checkbox/Checkbox.stories.tsx, packages/design-system-react-native/src/components/Checkbox/Checkbox.test.tsx, packages/design-system-react-native/src/components/Checkbox/Checkbox.tsx, packages/design-system-react-native/src/components/Checkbox/Checkbox.types.ts, packages/design-system-react-native/src/components/Checkbox/README.md, packages/design-system-react-native/src/components/Checkbox/index.ts, packages/design-system-react-native/src/components/index.ts
This PR adds the `Checkbox` component to the `@metamask/design-system-react-native` package
Fixes: #666 
1. Run `yarn storybook:ios`
2. Go to Components > Checkbox
3.
https://github.com/user-attachments/assets/6b6d15ab-261d-47ea-a4de-6b4e7f55282b
=> [DSRN] Added Checkbox

.prettierignore, packages/design-system-react/src/components/AvatarBase/AvatarBase.tsx, scripts/prepare-preview-builds.sh
This PR provides a hotfix for the publish previews pipeline by specifically targeting and updating imports for workspace packages that need to be modified during preview builds.
1. Reason for change: The current publish previews pipeline was incorrectly modifying all `@metamask/` imports, including regular dependencies like `@metamask/utils`, causing build failures.
2. Improvement/solution: Modified the `prepare-preview-builds.sh` script to:
- Only update specific package imports that need to be changed for previews
- Target exact package names instead of using a broad pattern
- Handle imports separately for each package based on their dependencies:
- `design-system-react-native`: Updates imports for `design-tokens` and `design-system-twrnc-preset`
- `design-system-twrnc-preset`: Updates …
=> fix: publish previews

packages/design-system-react-native/README.md, packages/design-system-react-native/package.json, packages/design-system-twrnc-preset/README.md, yarn.lock
Fixes:
1. Go to this page...
2.
3.
=> Draft: Test fix for dsrn release

scripts/create-package/utils.ts
Fixes a TypeScript compilation error in the create-package script where `prettierFormat` returns a Promise that wasn't being awaited. This was preventing the script from compiling and executing properly, causing the package creation workflow to fail.
Fixes: N/A
1. Run `yarn create-package --name test-package --description "Test package"`
2. Verify the script executes without TypeScript compilation errors
3. Confirm the new package is created successfully in the `packages/` directory
Script fails with TypeScript error:
```
TSError: ⨯ Unable to compile TypeScript:
scripts/create-package/utils.ts:138:5 - error TS2345: Argument of type 'Promise<string>' is not assignable to parameter of type 'string | ArrayBufferView | Iterable<string | ArrayBufferView> | AsyncIterable<string | …
```
=> fix: add await to prettierFormat call in create-package script

packages/design-system-react-native/src/components/temp-components/Blockies/Blockies.stories.tsx, packages/design-system-react-native/src/components/temp-components/Jazzicon/Jazzicon.stories.tsx, packages/design-system-react-native/src/components/temp-components/Maskicon/Maskicon.stories.tsx, packages/design-system-react/src/components/temp-components/Blockies/Blockies.stories.tsx, packages/design-system-react/src/components/temp-components/Blockies/README.mdx, packages/design-system-react/src/components/temp-components/Jazzicon/Jazzicon.stories.tsx, packages/design-system-react/src/components/temp-components/Maskicon/Maskicon.stories.tsx
Enhances Storybook stories for MaskIcon, Jazzicon, and Blockies components with comprehensive address format testing examples. This update adds extensive story examples that demonstrate how each icon component handles various address types including legacy formats, different blockchain networks (Ethereum, Bitcoin, Solana), and CAIP-10 standardized addresses across multiple networks. The enhanced stories enable visual verification that all three icon components generate consistent icons for equivalent addresses regardless of format.
Fixes: 
1. Start React Storybook with `yarn storybook`
2. Navigate to React Temp Components → MaskIcon → Address story
3. Verify the "CAIP-10 Format Consistency" section shows identical icons for the same Ethereum address across different networks (eip155:1, …
=> feat: enhance icon component stories with comprehensive address format testing

.github/workflows/lint-build-test.yml, scripts/prepare-preview-builds.sh
Updates build configuration to properly handle the design-system-shared package dependency across the monorepo. This change ensures that builds succeed by adding the necessary build step to the CI workflow and updating preview build scripts to correctly scope design-system-shared imports for both React and React Native packages.
Larger PR: https://github.com/MetaMask/metamask-design-system/pull/816
1. Verify CI workflow runs successfully with the added build step:
- Create a test PR and ensure the `lint-build-test` workflow passes
- Confirm that `yarn build` completes before running package tests
2. Test preview build generation:
- Comment `@metamaskbot publish-preview` on a test PR
- Verify preview packages are generated with correct scoped imports
- Check that …
=> fix: update build pipeline to include design-system-shared package
